[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "14"
  # Add any other environment variables your React app needs, for example:
  # REACT_APP_API_URL = "https://your-heroku-backend.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# If you need to ignore certain files or directories during deployment, you can use:
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
# [build.processing.html]
#   pretty_urls = true
# [build.processing.images]
#   compress = true